FROM httpd:2.4
MAINTAINER pacifica team 2
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
COPY livraison/frontend/  /usr/local/apache2/htdocs/
#COPY ./.htaccess /usr/local/apache2/htdocs/.htaccess
EXPOSE 80
